version: '3.7'

services:
  cf_catalogo:
    build: 
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    working_dir: /app
    command: sh run.sh
    ports:
      - 8080:8080
      - 8005:8005
    networks:
      - cf_network
  
  cf_mysqldb:
    image: mysql:latest
    environment: 
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=cf_catalogo_dev
      # - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    security_opt:
      - seccomp:unconfined
    ports: 
      - 3307:3306
    networks:
      - cf_network
  
networks:
  cf_network: 